// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package repository

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name) 
VALUES 
	(?)
RETURNING tenant_id, name
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.TenantID, &i.Name)
	return i, err
}
